USE [master]
GO
/****** Object:  Database [ImageUploadDB]    Script Date: 31-10-2023 11:14:00 ******/
CREATE DATABASE [ImageUploadDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ImageUploadDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ImageUploadDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ImageUploadDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ImageUploadDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [ImageUploadDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ImageUploadDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ImageUploadDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ImageUploadDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ImageUploadDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ImageUploadDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ImageUploadDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [ImageUploadDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ImageUploadDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ImageUploadDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ImageUploadDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ImageUploadDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ImageUploadDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ImageUploadDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ImageUploadDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ImageUploadDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ImageUploadDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [ImageUploadDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ImageUploadDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ImageUploadDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ImageUploadDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ImageUploadDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ImageUploadDB] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [ImageUploadDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ImageUploadDB] SET RECOVERY FULL 
GO
ALTER DATABASE [ImageUploadDB] SET  MULTI_USER 
GO
ALTER DATABASE [ImageUploadDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ImageUploadDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ImageUploadDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ImageUploadDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ImageUploadDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ImageUploadDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'ImageUploadDB', N'ON'
GO
ALTER DATABASE [ImageUploadDB] SET QUERY_STORE = OFF
GO
USE [ImageUploadDB]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 31-10-2023 11:14:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Images]    Script Date: 31-10-2023 11:14:00 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Images](
	[ImageId] [int] IDENTITY(1,1) NOT NULL,
	[ImageTitle] [nvarchar](50) NOT NULL,
	[ImageName] [nvarchar](200) NOT NULL,
 CONSTRAINT [PK_Images] PRIMARY KEY CLUSTERED 
(
	[ImageId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [ImageUploadDB] SET  READ_WRITE 
GO
